name: Microservice Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    producer-test:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "corretto"
            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3
            - name: Run test suites
              run: gradle :producer:test
    consumer-test:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "corretto"
            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3
            - name: Run test suites
              run: gradle :consumer:test
    regex-manager-test:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "corretto"
            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3
            - name: Run test suites
              run: gradle :regexManager:test
    elasticsearch-manager-test:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "corretto"
            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3
            - name: Run test suites
              run: gradle :elasticsearchManager:test
    search-service-test:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Setup JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "corretto"
            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3
            - name: Run test suites
              run: gradle :searchService:test
